#######################################################################################################
# Container definitions
#######################################################################################################
services:
  dtgbotmenu:
    container_name: dtgbotmenu
    restart: on-failure
    image: dtgbotmenu:latest                                       # See build instructions in dtgbot_image.txt
    environment:
      - TZ=Europe/Amsterdam                                            # Timezone setting
      - DomoticzURL=http://dtgbot:domoticz@localhost:8080              # your domoticz url
      - TelegramBotToken=121212121:Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  # your bottoken
    ports:
      - "8099:8099"                        # External port to use on the host. default 8099
    volumes:
      - /opt/dtgbot/data:/data             # Mapping of local folder data    to /opt/dtgbot/data
      - /opt/dtgbot/modules:/modules       # Mapping of local folder modules to /opt/dtgbot/modules
    healthcheck:  # restart container when dtgbot is hanging in the longpoll
      test: if [[ $(($(date +%s) - $(date -r "/tmp/dtgloop.txt" +%s))) -gt 40 ]]; then echo 0; kill 1; exit 1; else echo "Ok"; fi
      interval: 10s
      start_period: 30s
      timeout: 2s
      retries: 0
